language: node_js
node_js:
  - "10.15.3"

cache: yarn

install:
  - yarn install

matrix:
  include:
    - name: "Blog Pipeline"
      env: PACKAGE_LOCATION=packages/blog
    - name: "Shop Pipeline"
      env: PACKAGE_LOCATION=packages/shop


script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PACKAGE_LOCATION; then yarn test && yarn build else echo "$PACKAGE_LOCATION is NOT being built"; fi