language: node_js
node_js:
  - "10.15.3"

notifications:
    email: false

branches:
    only:
        - master
matrix:
    include:
        - env: TARGET=packages/blog
        - env: TARGET=packages/shop

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "$TARGET is being built" && cd $TARGET && yarn install && yarn build; else echo "$TARGET is NOT being built"; fi